name: hamr2018
dependencies:
  - python==3.6.5
  - numpy==1.15.1
  - matplotlib==2.2.3
  - jupyter==1.0.0
  - pandas==0.23.4
  - scipy==1.1.0
  - scikit-learn==0.19.2
  - pip:
    - pretty_midi==0.2.8
    - librosa==0.6.2
    - nbstripout
